[package]
name = "settings"
version = "0.1.0"
authors = ["allemanfredi <alle.manfredi@gmail.com>"]
edition = "2018"

[dependencies]
serde =  { version ="1.0.112", features = ["derive"] }
serde_json = "1.0.55"
utils = { package = "utils", path = "../utils" }